version: "3.8"

services:
  mito-api:
    image: mito:latest
    container_name: mito-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL:-mysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql:$MYSQL_PORT/$MYSQL_DATABASE}
    volumes:
      - ./data/django/staticfiles:/opt/mito/core/staticfiles
      - ./data/logs/api:/var/log/gunicorn
      - ./mito:/opt/mito
    networks:
      - mito_network
    depends_on:
      - mysql
    command: development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

  mito-worker:
    image: mito:latest
    container_name: mito-worker
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL:-mysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql:$MYSQL_PORT/$MYSQL_DATABASE}
      CELERY_AUTORELOAD: true
    volumes:
      - ./cache:/opt/cache
      - ./data/logs/worker:/var/log/celery
      - ./mito:/opt/mito
    networks:
      - mito_network
    depends_on:
      mito-api:
        condition: service_started
      mysql:
        condition: service_started
      redis:
        condition: service_started
    command: celery

  mito-scheduler:
    image: mito:latest
    container_name: mito-scheduler
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL:-mysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql:$MYSQL_PORT/$MYSQL_DATABASE}
      CELERY_AUTORELOAD: true
    volumes:
      - ./data/logs/scheduler:/var/log/celery
      - ./mito:/opt/mito
    networks:
      - mito_network
    depends_on:
      mito-api:
        condition: service_started
      mysql:
        condition: service_started
      redis:
        condition: service_started
    command: celery-beat

  mysql:
    image: mariadb:11.6
    container_name: mito-mariadb
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./docker/mysql/etc/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./data/mysql/data:/var/lib/mysql
      - ./data/logs/mysql:/var/log/mysql
    networks:
      - mito_network

  redis:
    image: redis:alpine
    container_name: mito-redis
    restart: unless-stopped
    command: redis-server
    volumes:
      - ./data/redis:/data
      - ./data/logs/redis:/var/log/redis
    networks:
      - mito_network

  flower:
    image: mito:latest
    container_name: mito-flower
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5555:5555"
    depends_on:
      mito-api:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - mito_network
    command: flower

networks:
  mito_network:
    driver: bridge
